# Bases temporales

este documento contiene ejemplos utilizar la funcion lispace de la libreria numpy para la creacion de bases temporales 

# Importar libreria para base temoral

In [1]:
import numpy as np

# utilizando la funcion np.linesace para crear un vector de tiempo

los datos necesarios para la funcion linespace son: valor inicial, valor final y numero de valores

In [9]:
valor_inicial = 0 # momento  en que se define el inicio del tiempo en segundos
valor_final = 2 # momento en que terminara el tiempo en segundos
numero_datos = 21 # numero de datos de el totoal del tiempo

tiempo = np.linspace(valor_inicial, valor_final, numero_datos)
tiempo

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

### utilizando distintos valores

In [8]:
valor_inicial = 0
valor_final = 15
numero_datos = 19

tiempo_2 = np.linspace(valor_inicial, valor_final, numero_datos)
tiempo_2

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        , 10.83333333, 11.66666667,
       12.5       , 13.33333333, 14.16666667, 15.        ])

In [12]:
tiempo_3 = np.linspace(valor_inicial, valor_final, numero_datos)
tiempo_3

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

# base temporal para una señal biologica de un csv

In [13]:
import pandas as pd

In [18]:
data_emg = pd.read_csv('C:/users/totuf/desktop/awa/EloEMG.csv', sep=';')
GM = data_emg.iloc[:,2].values
data_emg

Frame  Sub Frame        GM        SL
0          1          0 -0.016327  0.045509
1          1          1 -0.016174  0.037422
2          1          2 -0.010452  0.021973
3          1          3 -0.006142 -0.009537
4          1          4 -0.004082 -0.047760
...      ...        ...       ...       ...
63645   6365          5  0.007095 -0.014191
63646   6365          6  0.003777 -0.004997
63647   6365          7 -0.005302  0.004158
63648   6365          8 -0.030136  0.017815
63649   6365          9 -0.048943  0.029182

[63650 rows x 4 columns]

In [28]:
valor_inicial = 0
valor_final = len(GM)/1000
numero_datos = len(GM)

tiempo_gm = np.linspace(valor_inicial, valor_final, numero_datos)
print(tiempo_gm)

[0.00000000e+00 1.00001571e-03 2.00003142e-03 ... 6.36480000e+01
 6.36490000e+01 6.36500000e+01]


# siguente titulo

ahora tocaria seguir con la parte de la grafuicacion o tmb se podria hacer el orden de: graficacion, basestemporales y graficacion con bases temporales.
sio la otra opcion es separar totalmente los temas y y al graficar solo explicar que el eje x lo usamos comunmente como el tiempo y que en eso calza nuestra base temporal